### ISSUE TITLE
crear colleccion `publication type` para peru y enlazar con projectos y propiedades

### ISSUE THREAD

**Issue by juliorafaelr** [juliorafaelr/t-dashboard-api#57]

**Comment by stevensgsp** [comment]
Hecho. Lista la modificación en la base de datos `dashboard-peru`, 
Creada nueva collection `publication_types` con dos registros (`venta` y `alquiler`), 
Creado nuevo campo `publication_type_id` en las siguientes collections: 

1. `property_links`, 
2. `project_links`, 
3. `projects`, 
4. `properties`; 

Eliminado el antiguo campo publicatipn_type (enum),
Y hecha la asociación según el tipo de publicación de cada documento.

**Comment by stevensgsp** [comment]
Se cierra la tarea.
